### ISSUE TITLE
form-params versus json body

### ISSUE THREAD

**Issue by bombaywalla** [timothypratley/happyapi#7]
It seems that some providers require using `form-params` and a content-type of `application/x-www-form-urlencoded` for the parameters (instead of using the JSON body) during the Issue Access Token and Access Token Renewal phases of the OAuth exchange.  In fact, RFC 6749 only mentions the form params content-type and does not mention anything about the JSON body.

HappyAPI appears to only use the JSON body.

I can see two possible approaches to addressing this issue.  One is to switch to using `application/x-www-form-urlencoded` and `form-params` always.  The other is to provide a config option to choose one or the other per provider.

I'm happy to work on a PR for either of the approaches.

**Comment by timothypratley** [comment]
Thank you for pointing that out.

I agree we should switch to form-params.

That would be great if you could make a PR - thank you!

**Comment by timothypratley** [comment]
Thank you @bombaywalla
