### ISSUE TITLE
happyapi.edn as resource instead of file?

### ISSUE THREAD

**Issue by bombaywalla** [timothypratley/happyapi#9]
Currently, the `happyapi.edn` config is read as as a file.
What do you think about making it a resource instead?
That way, it can be place anywhere on the classpath and included in a jar file.

Happy to make a PR if you agree.

**Comment by timothypratley** [comment]
It would be great to look for it in both places, see `happyapi.setup/find-config` currently it looks in the environment and for a file, I think looking for a resource as well would be great.
PR welcome 😄

**Comment by bombaywalla** [comment]
I was thinking that the priority should be (in decreasing order): environment, file, resource.
What do you think?

**Comment by timothypratley** [comment]
💯 I like it 😄 yes

**Comment by timothypratley** [comment]
thank you
